// <auto-generated />
namespace Mvc5Project.Migrations.BlogDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Blog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blog));
        
        string IMigrationMetadata.Id
        {
            get { return "201511020458106_Blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
